### ISSUE TITLE
REQUEST: @Store("main")

### ISSUE THREAD

**Issue by kktos** [Zolyn/pinia-store-decorators#24]
Hi,
instead of doing
```typescript
@Store
class MainStore {
[ ... ]
export const useMainStore = defineStore(createOptions('main', MainStore));
```
it would be nice to be able to do
```typescript
@Store("main")
class MainStore {
[ ... ]
export const useMainStore = defineStore(createOptions(MainStore));
```

**Comment by Zolyn** [comment]
我之前有想过这种写法，但不确定会对与pinia的类型兼容性有什么影响，所以没有采取它。
顺带一提，你在上面提到的写法是v1（pinia-store-decorators）而不是v2（pinia-class-transformer）版的。

这个项目的工作原理本质上是将Class转换成`defineStore()`函数的options参数，它通过一个helper函数来实现。

在v1中，我并没有找到分离一个Class中的属性和getter的类型的方法，所以转换后的类型实际上getters同样被视作为了state（如果你没有编写同名的setter，它是能正常工作的），并且，它不支持使用类似`watch, watchEffect`的Composition API，因此我编写了v2

在v2中，定义Store的写法有些不同，States作为一个Class，Getters和Actions作为一个Class，你可以在名为`setup`的Action中使用Composition API对Store的各种数据进行处理，并且它不使用装饰器，因为装饰器所做的工作可以交给helper函数来做。
```typescript
import { defineStore } from 'pinia';
import { StoreFragment, transformClass } from 'pinia-class-transformer';

class State {
  counter = 0;
  name = 'Eduardo';
}

class Main  extends StoreFragment<State, Main> {
  get doubleCount(): number {
    return this.state.counter * 2;
  }

  get doubleCountPlusOne(): number {
    return this.state.counter * 2 + 1;
  }

  reset(): void {
    this.state.counter = 0;
    // Access the original ref
    this.wrappedStore.counter.value = 0;
  }
}

export const useMainStore = defineStore('main', transformClass({ state: State, fragment: Main }));
```
说实话，我并没想到会有人注意到或者使用这个项目。这个项目最初是写来给自己用的，同时积累一些TypeScript知识。
我不知道使用它是否会对性能造成影响，如果你要在生产环境上使用它，请慎重考虑。


---
（Translated by machine）

I had thought about this before, but wasn't sure how it would affect type compatibility with Pinia, so I didn't take it.
BTW, the code you mentioned above is v1 (Pinia-store-decorators) not V2 (Pinia-class-transformer).

The project essentially works by converting class to the options argument of 'defineStore()', which is implemented through a helper function.

In v1, I didn't find a way to separate the type of a property in a Class from that of a getter, so the converted type actually getters is treated as state as well (it works fine if you don't write a setter with the same name).
Also, it doesn't support using Composition APIs like 'Watch' and 'watchEffect', so I wrote V2.

In V2, Store definitions are written a little differently. States are wrapped by one class, Getters and Actions by another.
You can use the Composition API in an Action called 'setup' to manipulate the Store data. And it doesn't use decorators, because the work done by decorators can be left to helper functions.

```typescript
import { defineStore } from 'pinia';
import { StoreFragment, transformClass } from 'pinia-class-transformer';

class State {
  counter = 0;
  name = 'Eduardo';
}

class Main  extends StoreFragment<State, Main> {
  get doubleCount(): number {
    return this.state.counter * 2;
  }

  get doubleCountPlusOne(): number {
    return this.state.counter * 2 + 1;
  }

  reset(): void {
    this.state.counter = 0;
    // Access the original ref
    this.wrappedStore.counter.value = 0;
  }
}

export const useMainStore = defineStore('main', transformClass({ state: State, fragment: Main }));
```

TBH, I didn't think anyone would notice or use this project. The project was originally written for my own use, and I was able to build up some TypeScript knowledge in the process.

Actually, I don't know whether it will affect performance. If you're going to use it in a production environment, think carefully before using it.

**Comment by Zolyn** [comment]
现阶段项目仍有很多需要改进的地方，我会考虑兼容v1的写法（无装饰器）。


---



At the present stage, the project still needs to be improved. I will consider the writing method compatible with V1 (But no decorators).
